### ISSUE TITLE
saving policy with mab_experiment script

### ISSUE THREAD

**Issue by gekinci** [Chanlaw/assistive-bandits#1]
Hi, I am trying to reproduce your results. I ran mab_experiments.py and in .../data/50/eps-opt folder, I see .txt and .csv files generated. But there is no policy saved. How can I save/find the policy to evaluate? Thanks in advance.

**Comment by Chanlaw** [comment]
Hi gekinci,

I believe the policies are actually being stored by default using rllab, and should be somewhere in `.../rllab/data/...`. If you used install.sh, it should be in `assistive-bandits/src/rllab/data/local/`.

**Comment by gekinci** [comment]
I found them, thanks a lot.
